# Generated by Django 5.0.6 on 2025-01-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='exhibitionartwork',
            name='artwork',
        ),
        migrations.DeleteModel(
            name='Audit',
        ),
        migrations.RemoveField(
            model_name='exhibitionartwork',
            name='exhibition',
        ),
        migrations.RemoveField(
            model_name='virtualexhibition',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
        migrations.DeleteModel(
            name='ExhibitionArtwork',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='VirtualExhibition',
        ),
    ]
