# Generated by Django 5.0.6 on 2025-01-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Social', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edited_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
